/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Generate YouTube Title': ApiRouteHandler<{ email: string; channel: string }, unknown, { topic: 'youtube.title'; data: { jobId: string; email: string; channel: string } }>
    'YouTube Event': EventHandler<{ jobId: string; email: string; channel: string }, never>
  }
}